name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  # github-metrics:
  #   runs-on: ubuntu-latest
  #   environment: 
  #     name: prod
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: lowlighter/metrics@latest
  #       with:
  #         token: ${{ secrets.METRICS_TOKEN }}
  build:
    runs-on: ubuntu-latest
    environment: 
       name: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Configure pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt
      - name: Update README file
        env:
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python today.py
      - name: Commit
        run: |-
          git config --global user.name "ShreyW"
          git add .
          git diff
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
